version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.4.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - 9200:9200
  kibana:
    image: kibana:8.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
